[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.29.29"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
